
name: Verify Collection
on: [push]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Check out your code
    
    - name: Check collection exists
      run: |
        echo "Verifying collection file..."
        if [ -f "collections/Restful Booker_Booking API.postman_collection.json" ]; then
          echo "✅ Collection file found"
        else
          echo "❌ Collection file missing!"
          exit 1
        fi
        
    - name: Install Newman
      run: npm install -g newman
      
    - name: Run basic test
      run: |
        newman run "collections/Restful Booker_Booking API.postman_collection.json" \
          --reporters cli \
          --folder "Positive EndPoints"  # Only run specific folder