name: API Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '14'
    - run: npm install
    - run: npm run test-with-report
    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: api-test-report
        path: reports/