name: Postman CLI Tests
on: [push]

jobs:
  postman-tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Postman CLI
      run: |
        powershell -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
        postman --version
        
    - name: Login to Postman
      run: |
        postman login --with-api-key "${{ secrets.POSTMAN_API_KEY }}"
        
    - name: Get Restful-Booker Token
      id: auth
      run: |
        $response = Invoke-RestMethod -Uri "https://restful-booker.herokuapp.com/auth" `
          -Method Post `
          -Headers @{"Content-Type"="application/json"} `
          -Body '{"username":"admin","password":"password123"}'
        echo "token=$($response.token)" >> $env:GITHUB_OUTPUT
        
    - name: Run Tests
      run: |
        postman collection run "46202318-64c42902-9251-4dde-8565-069da344a26c" `
          --env-var "auth_token=${{ steps.auth.outputs.token }}" `
          --delay-request 1000
