name: API Tests
on: [push]
jobs:
  test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Postman CLI
      run: |
        powershell.exe -NoProfile -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://dl-cli.pstmn.io/install/win64.ps1'))"
    
    - name: Login to Postman
      run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
    
    - name: Run tests
      run: newman run "collections/test_collection.json"
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: reports/